version: "3.8"

services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./local-redis/data/:/data
      - ./redis-stack.conf:/redis-stack.conf

volumes:
  local-redis:
